# Generated by Django 4.2.1 on 2023-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
