# Generated by Django 4.2.1 on 2023-05-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_post_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
    ]
